"""
drug_dict.py — NLP drug dictionary for WATNEY search.

Contains DRUG_DICT_JS: a raw JavaScript string defining the DRUGS object
(canonical name -> list of aliases) used by the NLP search bar.

Import in watney_v6.py:
    from drug_dict import DRUG_DICT_JS
"""

DRUG_DICT_JS = r"""
var DRUGS = {
  // ── Oncology: Alkylating agents ──────────────────────────────────────────
  "temozolomide":["temodar","tmz","temomodal"],
  "carmustine":["bcnu","bicnu","gliadel","bis-chloroethylnitrosourea"],
  "lomustine":["ccnu","gleostine","ceenu"],
  "nimustine":["acnu"],
  "fotemustine":["muphoran"],
  "streptozocin":["zanosar"],
  "dacarbazine":["dtic","dtic-dome"],
  "procarbazine":["matulane","natulan"],
  "cyclophosphamide":["cytoxan","neosar","endoxan","ctx"],
  "ifosfamide":["ifex","holoxan"],
  "melphalan":["alkeran","evomela","lpam"],
  "chlorambucil":["leukeran"],
  "busulfan":["myleran","busulfex"],
  "bendamustine":["treanda","belrapzo","levact"],
  "thiotepa":["thioplex","tepadina"],
  "altretamine":["hexalen","hexamethylmelamine"],
  "estramustine":["emcyt"],
  "uramustine":["uracil mustard"],
  "semustine":["methyl-ccnu"],
  // ── Platinum agents ──────────────────────────────────────────────────────
  "cisplatin":["platinol","cddp","platinol-aq"],
  "carboplatin":["paraplatin","cbdca"],
  "oxaliplatin":["eloxatin"],
  "nedaplatin":["aqupla"],
  "satraplatin":["jm-216"],
  "picoplatin":["jm-118"],
  // ── Antimetabolites ──────────────────────────────────────────────────────
  "methotrexate":["mtx","rheumatrex","trexall","amethopterin","otrexup"],
  "capecitabine":["xeloda"],
  "fluorouracil":["5-fu","adrucil","efudex","carac","5-fluorouracil"],
  "gemcitabine":["gemzar","infugem"],
  "cytarabine":["ara-c","cytosar","depocyt","cytosine arabinoside"],
  "azacitidine":["vidaza","azacytidine","5-azacitidine","onureg"],
  "decitabine":["dacogen","5-azadeoxycytidine"],
  "cladribine":["leustatin","2-cda","mavenclad"],
  "fludarabine":["fludara","fludarabine phosphate"],
  "clofarabine":["clolar","clofarex"],
  "nelarabine":["arranon","ara-g"],
  "pemetrexed":["alimta"],
  "pralatrexate":["folotyn"],
  "hydroxyurea":["hydrea","droxia","mylocel"],
  "thioguanine":["tabloid","6-tg","6-thioguanine"],
  "mercaptopurine":["purinethol","purixan","6-mp"],
  "tegafur":["uftoral","ts-1"],
  "trifluridine":["lonsurf","tas-102"],
  "trimetrexate":["neutrexin"],
  "raltitrexed":["tomudex"],
  "sapacitabine":["cndac"],
  // ── Topoisomerase inhibitors ─────────────────────────────────────────────
  "irinotecan":["camptosar","cpt-11","campto","onivyde"],
  "topotecan":["hycamtin","skycampta"],
  "etoposide":["vp-16","etopophos","toposar","vepesid"],
  "teniposide":["vumon","vm-26"],
  "belotecan":["camtobell"],
  "lurtotecan":["gjj-111"],
  // ── Taxanes ──────────────────────────────────────────────────────────────
  "paclitaxel":["taxol","onxol","abraxane","nab-paclitaxel"],
  "docetaxel":["taxotere","docefrez"],
  "cabazitaxel":["jevtana"],
  "nab-paclitaxel":["abraxane","albumin-bound paclitaxel"],
  "paclitaxel poliglumex":["opaxio","xyotax"],
  "larotaxel":["rpm-16"],
  "ortataxel":["idm-202"],
  // ── Vinca alkaloids ──────────────────────────────────────────────────────
  "vincristine":["oncovin","vincasar","vcr"],
  "vinblastine":["velban","velbe","vbl"],
  "vinorelbine":["navelbine","nvb"],
  "vindesine":["eldisine","vds"],
  "vinflunine":["javlor"],
  // ── Anthracyclines ───────────────────────────────────────────────────────
  "doxorubicin":["adriamycin","rubex","hydroxydaunorubicin","hdx"],
  "doxil":["liposomal doxorubicin","pld","doxorubicin liposomal","caelyx","myocet"],
  "epirubicin":["ellence","pharmorubicin"],
  "idarubicin":["idamycin"],
  "daunorubicin":["cerubidine","daunomycin","rubidomycin"],
  "liposomal daunorubicin":["daunoxome"],
  "mitoxantrone":["novantrone","dhad"],
  "valrubicin":["valstar"],
  "pixantrone":["pixuvri"],
  "amrubicin":["calsed"],
  // ── Antitumor antibiotics ────────────────────────────────────────────────
  "bleomycin":["blenoxane"],
  "mitomycin":["mutamycin","mitozytrex","mmc"],
  "actinomycin":["cosmegen","dactinomycin","act-d"],
  "plicamycin":["mithracin","mithramycin"],
  "trabectedin":["yondelis","ecteinascidin"],
  "lurbinectedin":["zepzelca"],
  // ── EGFR inhibitors ──────────────────────────────────────────────────────
  "erlotinib":["tarceva"],
  "gefitinib":["iressa"],
  "afatinib":["gilotrif"],
  "osimertinib":["tagrisso"],
  "lapatinib":["tykerb"],
  "neratinib":["nerlynx"],
  "tucatinib":["tukysa"],
  "dacomitinib":["vizimpro"],
  "cetuximab":["erbitux"],
  "panitumumab":["vectibix"],
  "necitumumab":["portrazza"],
  "amivantamab":["rybrevant"],
  "mobocertinib":["exkivity"],
  "poziotinib":["njs-100"],
  "olmutinib":["olita"],
  "rociletinib":["co-1686"],
  // ── ALK inhibitors ───────────────────────────────────────────────────────
  "crizotinib":["xalkori"],
  "alectinib":["alecensa"],
  "brigatinib":["alunbrig"],
  "lorlatinib":["lorbrena"],
  "ceritinib":["zykadia"],
  "ensartinib":["x-396"],
  // ── VEGF/VEGFR inhibitors ────────────────────────────────────────────────
  "bevacizumab":["avastin","bev","mvasi","zirabev"],
  "ramucirumab":["cyramza"],
  "axitinib":["inlyta"],
  "sunitinib":["sutent"],
  "sorafenib":["nexavar"],
  "pazopanib":["votrient"],
  "lenvatinib":["lenvima","e7080"],
  "regorafenib":["stivarga"],
  "cabozantinib":["cabometyx","cometriq","xl184"],
  "vandetanib":["caprelsa","zactima"],
  "tivozanib":["fotivda"],
  "ziv-aflibercept":["zaltrap"],
  "fruquintinib":["elunate"],
  "anlotinib":["al3818"],
  "apatinib":["rivoceranib","yervoy"],
  "nintedanib":["ofev","vargatef"],
  "cediranib":["recentin","az2171"],
  "motesanib":["amg-706"],
  "telatinib":["bay-57-9352"],
  "semaxanib":["su5416"],
  "vatalanib":["ptk787"],
  // ── RAS/RAF/MEK/ERK inhibitors ───────────────────────────────────────────
  "vemurafenib":["zelboraf"],
  "dabrafenib":["tafinlar"],
  "encorafenib":["braftovi"],
  "trametinib":["mekinist"],
  "cobimetinib":["cotellic"],
  "binimetinib":["mektovi"],
  "selumetinib":["koselugo"],
  "sotorasib":["lumakras","amg-510"],
  "adagrasib":["krazati","mrtx849"],
  "belvarafenib":["hm95573"],
  "lifirafenib":["bpi-lm-003"],
  "ulixertinib":["bvd-523"],
  "ravoxertinib":["gdc-0994"],
  "mirdametinib":["pd-0325901"],
  "pimasertib":["as703026"],
  "refametinib":["bay86-9766"],
  // ── BCR-ABL/KIT/PDGFR ───────────────────────────────────────────────────
  "imatinib":["gleevec","glivec","sti571"],
  "dasatinib":["sprycel"],
  "nilotinib":["tasigna"],
  "bosutinib":["bosulif"],
  "ponatinib":["iclusig"],
  "asciminib":["scemblix"],
  "avapritinib":["ayvakit"],
  "ripretinib":["qinlock"],
  "pexidartinib":["turalio"],
  "masitinib":["ab1010"],
  "radotinib":["supect"],
  "rebastinib":["dcc-2036"],
  // ── CDK inhibitors ───────────────────────────────────────────────────────
  "palbociclib":["ibrance"],
  "ribociclib":["kisqali"],
  "abemaciclib":["verzenio"],
  "trilaciclib":["cosela"],
  "dinaciclib":["sch-727965"],
  "flavopiridol":["alvocidib"],
  "seliciclib":["r-roscovitine","cyc202"],
  "voruciclib":["p1446a-05"],
  "lerociclib":["g1t38"],
  // ── mTOR inhibitors ──────────────────────────────────────────────────────
  "everolimus":["afinitor","zortress","rad001"],
  "temsirolimus":["torisel","cci-779"],
  "sirolimus":["rapamune","rapamycin"],
  "ridaforolimus":["deforolimus","ap23573"],
  "sapanisertib":["ink128","mlnc0628"],
  "vistusertib":["azd2014"],
  "torin1":["torin-1"],
  // ── PI3K inhibitors ──────────────────────────────────────────────────────
  "idelalisib":["zydelig"],
  "copanlisib":["aliqopa"],
  "alpelisib":["piqray"],
  "umbralisib":["ukoniq"],
  "duvelisib":["copiktra"],
  "parsaclisib":["incmga00012"],
  "buparlisib":["bkm120"],
  "taselisib":["gdc-0032"],
  "pictilisib":["gdc-0941"],
  "pilaralisib":["xp-765"],
  "gedatolisib":["pk1-587"],
  "tenalisib":["rp6530"],
  // ── PARP inhibitors ──────────────────────────────────────────────────────
  "olaparib":["lynparza"],
  "niraparib":["zejula"],
  "rucaparib":["rubraca"],
  "talazoparib":["talzenna"],
  "veliparib":["abb-888"],
  "pamiparib":["bg4-530"],
  "fuzuloparib":["cys-9722"],
  "senaparib":["itk-001"],
  // ── Checkpoint inhibitors PD-1/PD-L1 ────────────────────────────────────
  "pembrolizumab":["keytruda","pembro","mk-3475"],
  "nivolumab":["opdivo","nivo"],
  "cemiplimab":["libtayo"],
  "dostarlimab":["jemperli"],
  "atezolizumab":["tecentriq"],
  "durvalumab":["imfinzi"],
  "avelumab":["bavencio"],
  "sintilimab":["tyvyt"],
  "tislelizumab":["brukinsa-pd1"],
  "camrelizumab":["airuika"],
  "toripalimab":["tuoyi"],
  "spartalizumab":["pdro1","pdr001"],
  "balstilimab":["agen2034"],
  "retifanlimab":["zynyz"],
  "sugemalimab":["cob-y16"],
  // ── CTLA-4 inhibitors ────────────────────────────────────────────────────
  "ipilimumab":["yervoy","ipi"],
  "tremelimumab":["imjudo"],
  "zalifrelimab":["agen1884"],
  // ── LAG-3/TIM-3/TIGIT ────────────────────────────────────────────────────
  "relatlimab":["opdualag"],
  "favezelimab":["mk-4280"],
  "fianlimab":["regn3767"],
  "sabatolimab":["mbt-714"],
  "tiragolumab":["mab-7c4"],
  "vibostolimab":["mk-7684"],
  "domvanalimab":["ab154"],
  // ── HER2-targeted ────────────────────────────────────────────────────────
  "trastuzumab":["herceptin","tras","herzuma","kanjinti","ogivri"],
  "pertuzumab":["perjeta"],
  "ado-trastuzumab":["kadcyla","t-dm1","trastuzumab emtansine"],
  "trastuzumab deruxtecan":["enhertu","ds-8201","fam-trastuzumab deruxtecan"],
  "margetuximab":["margenza"],
  "zanidatamab":["zymontia","zw25"],
  "tucatinib":["tukysa"],
  // ── HDAC inhibitors ──────────────────────────────────────────────────────
  "vorinostat":["zolinza","saha"],
  "romidepsin":["istodax","fk228"],
  "panobinostat":["farydak","lbh589"],
  "belinostat":["beleodaq","pdx101"],
  "entinostat":["syndax"],
  "mocetinostat":["mgcd0103"],
  "tucidinostat":["chidamide","epidaza"],
  "resminostat":["4sc-201"],
  "givinostat":["itn090"],
  "abexinostat":["pci-24781"],
  // ── Proteasome inhibitors ────────────────────────────────────────────────
  "bortezomib":["velcade","ps-341"],
  "carfilzomib":["kyprolis"],
  "ixazomib":["ninlaro"],
  "marizomib":["npi-0052"],
  "oprozomib":["onx-0912"],
  // ── Immunomodulators (IMiDs) ─────────────────────────────────────────────
  "thalidomide":["thalomid"],
  "lenalidomide":["revlimid"],
  "pomalidomide":["pomalyst"],
  "mezigdomide":["cc-92480"],
  "iberdomide":["cc-220"],
  "avadomide":["cc-122"],
  // ── Anti-CD20 mAbs ───────────────────────────────────────────────────────
  "rituximab":["rituxan","mabthera","rtx","riabni","truxima"],
  "obinutuzumab":["gazyva"],
  "ofatumumab":["arzerra","kesimpta"],
  "ocrelizumab":["ocrevus"],
  "ublituximab":["briumvi"],
  "orelabrutinib":["izatimab"],
  // ── Anti-CD38/CD319 ──────────────────────────────────────────────────────
  "daratumumab":["darzalex","darzalex faspro"],
  "isatuximab":["sarclisa"],
  "elotuzumab":["empliciti"],
  // ── ADC (Antibody-Drug Conjugates) ───────────────────────────────────────
  "brentuximab vedotin":["adcetris","sgn-35"],
  "polatuzumab vedotin":["polivy"],
  "gemtuzumab ozogamicin":["mylotarg"],
  "inotuzumab ozogamicin":["besylate","besponsa"],
  "sacituzumab govitecan":["trodelvy"],
  "enfortumab vedotin":["padcev"],
  "tisotumab vedotin":["tivdak"],
  "loncastuximab tesirine":["zynlonta"],
  "mirvetuximab soravtansine":["elahere"],
  "telisotuzumab vedotin":["tel-ved"],
  "datopotamab deruxtecan":["dato-dxd"],
  "patritumab deruxtecan":["hhr3","her3-dxd"],
  "zilovertamab vedotin":["mk-2140"],
  "ladiratuzumab vedotin":["sgn-lgr5"],
  "camidanlumab tesirine":["adct-301"],
  // ── Bispecific antibodies ────────────────────────────────────────────────
  "blinatumomab":["blincyto"],
  "mosunetuzumab":["lunsumio"],
  "glofitamab":["columvi"],
  "epcoritamab":["epkinly"],
  "odronextamab":["regn1979"],
  "talquetamab":["talvey"],
  "teclistamab":["tecvayli"],
  "elranatamab":["elrexfio"],
  "linvoseltamab":["regn5458"],
  "cevostamab":["rg6160"],
  "inavolisib":["gdc-0077"],
  // ── BTK inhibitors ───────────────────────────────────────────────────────
  "ibrutinib":["imbruvica"],
  "acalabrutinib":["calquence"],
  "zanubrutinib":["brukinsa"],
  "pirtobrutinib":["jaypirca"],
  "tirabrutinib":["velexbru"],
  "spebrutinib":["avl-292"],
  "fenebrutinib":["gdc-0853"],
  // ── BCL-2 inhibitors ─────────────────────────────────────────────────────
  "venetoclax":["venclexta","abt-199"],
  "navitoclax":["abt-263"],
  "obatoclax":["gx15-070"],
  "pelcitoclax":["apm-1285"],
  // ── FLT3 inhibitors ──────────────────────────────────────────────────────
  "gilteritinib":["xospata"],
  "midostaurin":["rydapt"],
  "quizartinib":["vanflyta"],
  "crenolanib":["cp-868596"],
  "tandutinib":["mlnm518"],
  // ── IDH inhibitors ───────────────────────────────────────────────────────
  "ivosidenib":["tibsovo"],
  "enasidenib":["idhifa"],
  "olutasidenib":["rezlidhia"],
  "vorasidenib":["dag-idh"],
  // ── JAK/STAT inhibitors ──────────────────────────────────────────────────
  "ruxolitinib":["jakafi","jakavi"],
  "fedratinib":["inrebic"],
  "pacritinib":["vonjo"],
  "momelotinib":["ojjaara"],
  "baricitinib":["olumiant"],
  "tofacitinib":["xeljanz"],
  "upadacitinib":["rinvoq"],
  "filgotinib":["jyseleca"],
  "peficitinib":["smyraf"],
  "itacitinib":["itf2357"],
  // ── SMO/Hedgehog inhibitors ──────────────────────────────────────────────
  "vismodegib":["erivedge"],
  "sonidegib":["odomzo"],
  "glasdegib":["daurismo"],
  "taladegib":["ly2940680"],
  "patidegib":["ilp-107"],
  // ── RET inhibitors ───────────────────────────────────────────────────────
  "selpercatinib":["retevmo","loxo-292"],
  "pralsetinib":["gavreto","blu-667"],
  "vandetanib":["caprelsa"],
  // ── MET inhibitors ───────────────────────────────────────────────────────
  "capmatinib":["tabrecta"],
  "tepotinib":["tepmetko"],
  "savolitinib":["hmpl-504","volitinib"],
  "telisotuzumab":["tel-met"],
  "bozitinib":["syc-1461"],
  // ── NTRK inhibitors ──────────────────────────────────────────────────────
  "larotrectinib":["vitrakvi"],
  "entrectinib":["rozlytrek"],
  "repotrectinib":["tpx-0005"],
  "selitrectinib":["loxo-195"],
  "taletrectinib":["ab-106","dco-0701"],
  // ── KRAS inhibitors ──────────────────────────────────────────────────────
  "sotorasib":["lumakras","amg-510"],
  "adagrasib":["krazati","mrtx849"],
  "divarasib":["gdc-6036"],
  "glecirasib":["jdq443"],
  "BI 1701963":["bi1701963"],
  "LY3537982":["ly3537982"],
  // ── XPO1/Selinexor ───────────────────────────────────────────────────────
  "selinexor":["xpovio","kpt-330"],
  "eltanexor":["kpt-8602"],
  // ── EZH2 inhibitors ──────────────────────────────────────────────────────
  "tazemetostat":["tazverik"],
  "valemetostat":["ezhihibit"],
  "CPI-1205":["cpi-1205"],
  // ── Hormone / endocrine agents ───────────────────────────────────────────
  "tamoxifen":["nolvadex","soltamox"],
  "toremifene":["fareston"],
  "raloxifene":["evista"],
  "fulvestrant":["faslodex"],
  "letrozole":["femara"],
  "anastrozole":["arimidex"],
  "exemestane":["aromasin"],
  "megestrol":["megace"],
  "medroxyprogesterone":["provera","depo-provera"],
  "flutamide":["eulexin"],
  "bicalutamide":["casodex"],
  "nilutamide":["nilandron"],
  "enzalutamide":["xtandi"],
  "apalutamide":["erleada"],
  "darolutamide":["nubeqa"],
  "abiraterone":["zytiga","yonsa"],
  "leuprolide":["lupron","eligard","viadur"],
  "goserelin":["zoladex"],
  "triptorelin":["trelstar"],
  "buserelin":["suprecur"],
  "histrelin":["supprelin"],
  "degarelix":["firmagon"],
  "relugolix":["orgovyx"],
  "trilostane":["modrastane"],
  "mitotane":["lysodren"],
  "ketoconazole":["nizoral"],
  "aminoglutethimide":["cytadren"],
  "octreotide":["sandostatin"],
  "lanreotide":["somatuline"],
  "pasireotide":["signifor"],
  // ── Bisphosphonates / bone agents ────────────────────────────────────────
  "zoledronic acid":["zometa","reclast","zoledronate"],
  "pamidronate":["aredia"],
  "ibandronate":["boniva","bonviva"],
  "alendronate":["fosamax"],
  "risedronate":["actonel"],
  "clodronate":["bonefos"],
  "denosumab":["xgeva","prolia"],
  // ── Radiopharmaceuticals ─────────────────────────────────────────────────
  "radium-223":["xofigo","radium chloride"],
  "lutetium dotatate":["lutathera","lu-177-dotatate"],
  "lutetium psma":["pluvicto","lu-177-psma","lutetium vipivotide"],
  "iodine-131":["radioiodine","i-131"],
  "yttrium-90":["y-90","therasphere","sirspheres"],
  "samarium-153":["quadramet"],
  "strontium-89":["metastron"],
  // ── Misc targeted therapies ──────────────────────────────────────────────
  "belzutifan":["welireg"],
  "alisertib":["mln8237"],
  "naxitamab":["danyelza"],
  "dinutuximab":["unituxin"],
  "tagraxofusp":["elzonris"],
  "brexucabtagene autoleucel":["tecartus"],
  "axicabtagene ciloleucel":["yescarta","axi-cel"],
  "tisagenlecleucel":["kymriah"],
  "lisocabtagene maraleucel":["breyanzi","liso-cel"],
  "idecabtagene vicleucel":["abecma","ide-cel"],
  "ciltacabtagene autoleucel":["carvykti","cilta-cel"],
  "oportuzumab monatox":["vicinium"],
  "denileukin diftitox":["ontak"],
  "aldesleukin":["proleukin","il-2"],
  "interferon alfa":["intron-a","roferon-a","peg-intron"],
  "talimogene laherparepvec":["imlygic","t-vec"],
  "bacillus calmette-guerin":["bcg","tice","theracys"],
  "sipuleucel-t":["provenge"],
  "cemiplimab":["libtayo"],
  "atezolizumab":["tecentriq"],

  // ── 200 Common Medical Drugs & Treatments ────────────────────────────────
  // Analgesics / Pain
  "acetaminophen":["tylenol","paracetamol","panadol","ofirmev"],
  "ibuprofen":["advil","motrin","brufen","nurofen"],
  "aspirin":["asa","bayer","ecotrin","entrophen"],
  "naproxen":["aleve","naprosyn","anaprox"],
  "celecoxib":["celebrex"],
  "ketorolac":["toradol"],
  "indomethacin":["indocin","indometacin"],
  "diclofenac":["voltaren","cataflam"],
  "meloxicam":["mobic","vivlodex"],
  "morphine":["ms contin","avinza","kadian","roxanol"],
  "oxycodone":["oxycontin","percocet","roxicodone"],
  "hydrocodone":["vicodin","norco","zohydro"],
  "fentanyl":["duragesic","actiq","sublimaze","ionsys"],
  "hydromorphone":["dilaudid","exalgo"],
  "codeine":["tylenol with codeine","co-codamol"],
  "tramadol":["ultram","conzip","ultracet"],
  "buprenorphine":["suboxone","buprenex","butrans"],
  "methadone":["dolophine","methadose"],
  "tapentadol":["nucynta"],
  "pregabalin":["lyrica"],
  "gabapentin":["neurontin","gralise","horizant"],
  "duloxetine":["cymbalta"],
  // Antibiotics
  "amoxicillin":["amoxil","trimox","moxatag"],
  "amoxicillin-clavulanate":["augmentin","amoclav"],
  "ampicillin":["omnipen","principen"],
  "piperacillin-tazobactam":["zosyn","tazocin"],
  "azithromycin":["zithromax","z-pak","zmax"],
  "clarithromycin":["biaxin"],
  "erythromycin":["ery-tab","erythrocin"],
  "ciprofloxacin":["cipro","ciloxan"],
  "levofloxacin":["levaquin"],
  "moxifloxacin":["avelox"],
  "doxycycline":["vibramycin","monodox","doryx"],
  "minocycline":["minocin","dynacin","solodyn"],
  "tetracycline":["sumycin","achromycin"],
  "clindamycin":["cleocin"],
  "metronidazole":["flagyl","metrogel"],
  "vancomycin":["vancocin"],
  "linezolid":["zyvox"],
  "daptomycin":["cubicin"],
  "ceftriaxone":["rocephin"],
  "cefazolin":["ancef","kefzol"],
  "cefdinir":["omnicef"],
  "cephalexin":["keflex"],
  "trimethoprim-sulfamethoxazole":["bactrim","septra","cotrimoxazole","tmp-smx"],
  "nitrofurantoin":["macrobid","macrodantin"],
  "meropenem":["merrem"],
  "imipenem":["primaxin"],
  "ertapenem":["invanz"],
  "aztreonam":["azactam"],
  "rifampin":["rifadin","rimactane"],
  "isoniazid":["nydrazid","inh"],
  "ethambutol":["myambutol"],
  "pyrazinamide":["tebrazid"],
  "fluconazole":["diflucan"],
  "itraconazole":["sporanox"],
  "voriconazole":["vfend"],
  "posaconazole":["noxafil"],
  "micafungin":["mycamine"],
  "caspofungin":["cancidas"],
  "amphotericin b":["fungizone","ambisome","abelcet"],
  "acyclovir":["zovirax"],
  "valacyclovir":["valtrex"],
  "oseltamivir":["tamiflu"],
  "letermovir":["prevymis"],
  "ganciclovir":["cytovene"],
  "valganciclovir":["valcyte"],
  // Cardiovascular
  "metoprolol":["lopressor","toprol-xl"],
  "atenolol":["tenormin"],
  "carvedilol":["coreg"],
  "bisoprolol":["zebeta"],
  "propranolol":["inderal","innopran"],
  "lisinopril":["prinivil","zestril"],
  "enalapril":["vasotec"],
  "ramipril":["altace"],
  "captopril":["capoten"],
  "losartan":["cozaar"],
  "valsartan":["diovan"],
  "irbesartan":["avapro"],
  "candesartan":["atacand"],
  "amlodipine":["norvasc"],
  "nifedipine":["procardia","adalat"],
  "diltiazem":["cardizem","tiazac"],
  "verapamil":["calan","isoptin","verelan"],
  "furosemide":["lasix"],
  "hydrochlorothiazide":["hctz","microzide"],
  "spironolactone":["aldactone","carospir"],
  "chlorthalidone":["thalitone"],
  "digoxin":["lanoxin"],
  "amiodarone":["pacerone","cordarone"],
  "atorvastatin":["lipitor"],
  "rosuvastatin":["crestor"],
  "simvastatin":["zocor"],
  "pravastatin":["pravachol"],
  "ezetimibe":["zetia"],
  "warfarin":["coumadin","jantoven"],
  "apixaban":["eliquis"],
  "rivaroxaban":["xarelto"],
  "dabigatran":["pradaxa"],
  "edoxaban":["savaysa","lixiana"],
  "clopidogrel":["plavix"],
  "ticagrelor":["brilinta"],
  "prasugrel":["effient"],
  "heparin":["unfractionated heparin","ufh"],
  "enoxaparin":["lovenox","clexane"],
  "nitroglycerin":["nitrostat","nitro-bid","ntg"],
  "isosorbide mononitrate":["imdur","ismo"],
  "sacubitril-valsartan":["entresto"],
  "ivabradine":["corlanor"],
  // Diabetes / Endocrine
  "metformin":["glucophage","glumetza","fortamet"],
  "insulin glargine":["lantus","basaglar","toujeo"],
  "insulin aspart":["novolog","fiasp"],
  "insulin lispro":["humalog","admelog"],
  "insulin detemir":["levemir"],
  "glipizide":["glucotrol"],
  "glyburide":["diabeta","micronase"],
  "glimepiride":["amaryl"],
  "sitagliptin":["januvia"],
  "saxagliptin":["onglyza"],
  "linagliptin":["tradjenta"],
  "empagliflozin":["jardiance"],
  "dapagliflozin":["farxiga","forxiga"],
  "canagliflozin":["invokana"],
  "liraglutide":["victoza","saxenda"],
  "semaglutide":["ozempic","wegovy","rybelsus"],
  "dulaglutide":["trulicity"],
  "pioglitazone":["actos"],
  "rosiglitazone":["avandia"],
  "levothyroxine":["synthroid","levoxyl","tirosint"],
  "methimazole":["tapazole"],
  "propylthiouracil":["ptu"],
  "desmopressin":["ddavp","stimate"],
  "prednisone":["deltasone","rayos"],
  "prednisolone":["orapred","pediapred"],
  "dexamethasone":["decadron","dexasone"],
  "hydrocortisone":["cortef","solu-cortef"],
  "methylprednisolone":["solu-medrol","medrol"],
  "fludrocortisone":["florinef"],
  // Respiratory
  "albuterol":["proventil","ventolin","proair"],
  "salmeterol":["serevent"],
  "formoterol":["foradil","perforomist"],
  "tiotropium":["spiriva"],
  "ipratropium":["atrovent"],
  "budesonide":["pulmicort","rhinocort","uceris"],
  "fluticasone":["flovent","flonase","advair"],
  "montelukast":["singulair"],
  "theophylline":["theo-dur","uniphyl"],
  "roflumilast":["daliresp"],
  "benralizumab":["fasenra"],
  "mepolizumab":["nucala"],
  "dupilumab":["dupixent"],
  "omalizumab":["xolair"],
  // GI / Hepatic
  "omeprazole":["prilosec","losec"],
  "pantoprazole":["protonix","pantoloc"],
  "esomeprazole":["nexium"],
  "lansoprazole":["prevacid"],
  "ranitidine":["zantac"],
  "famotidine":["pepcid"],
  "ondansetron":["zofran"],
  "prochlorperazine":["compazine","stemetil"],
  "metoclopramide":["reglan","metozolv"],
  "domperidone":["motilium"],
  "loperamide":["imodium"],
  "lactulose":["constulose","kristalose"],
  "polyethylene glycol":["miralax","golytely"],
  "mesalamine":["asacol","pentasa","lialda"],
  "sulfasalazine":["azulfidine"],
  "infliximab":["remicade","inflectra","renflexis"],
  "adalimumab":["humira","amjevita"],
  "ustekinumab":["stelara"],
  "vedolizumab":["entyvio"],
  "ursodiol":["actigall","urso"],
  // Immunosuppressants / Rheumatology
  "methotrexate":["mtx","rheumatrex","trexall"],
  "azathioprine":["imuran"],
  "mycophenolate":["cellcept","myfortic"],
  "tacrolimus":["prograf","protopic"],
  "cyclosporine":["neoral","sandimmune","gengraf"],
  "hydroxychloroquine":["plaquenil"],
  "leflunomide":["arava"],
  "abatacept":["orencia"],
  "tocilizumab":["actemra"],
  "etanercept":["enbrel"],
  // Neurology / Psychiatry
  "levodopa-carbidopa":["sinemet","duopa","rytary"],
  "pramipexole":["mirapex"],
  "ropinirole":["requip"],
  "rasagiline":["azilect"],
  "selegiline":["eldepryl","emsam"],
  "donepezil":["aricept"],
  "memantine":["namenda"],
  "sertraline":["zoloft"],
  "fluoxetine":["prozac","sarafem"],
  "escitalopram":["lexapro"],
  "citalopram":["celexa"],
  "paroxetine":["paxil","pexeva"],
  "venlafaxine":["effexor"],
  "bupropion":["wellbutrin","zyban"],
  "mirtazapine":["remeron"],
  "amitriptyline":["elavil"],
  "nortriptyline":["pamelor"],
  "lorazepam":["ativan"],
  "alprazolam":["xanax"],
  "clonazepam":["klonopin"],
  "diazepam":["valium"],
  "zolpidem":["ambien"],
  "quetiapine":["seroquel"],
  "risperidone":["risperdal"],
  "olanzapine":["zyprexa"],
  "haloperidol":["haldol"],
  "lithium":["lithobid","eskalith"],
  "valproic acid":["depakote","depakene"],
  "lamotrigine":["lamictal"],
  "levetiracetam":["keppra"],
  "phenytoin":["dilantin","phenytek"],
  "carbamazepine":["tegretol","carbatrol"],
  "topiramate":["topamax"],
  "oxcarbazepine":["trileptal"],
  "lacosamide":["vimpat"],
  // Antiemetics / Supportive
  "dexamethasone":["decadron"],
  "aprepitant":["emend"],
  "fosaprepitant":["emend iv"],
  "netupitant-palonosetron":["akynzeo"],
  "palonosetron":["aloxi"],
  "granisetron":["kytril","sancuso"],
  "haloperidol":["haldol"],
  "lorazepam":["ativan"],
  "dronabinol":["marinol","syndros"],
  // Growth factors / Supportive onc
  "filgrastim":["neupogen","zarxio","nivestym"],
  "pegfilgrastim":["neulasta","fulphila","ziextenzo"],
  "sargramostim":["leukine"],
  "epoetin alfa":["epogen","procrit"],
  "darbepoetin alfa":["aranesp"],
  "eltrombopag":["promacta"],
  "romiplostim":["nplate"],
  "oprelvekin":["neumega"],
  "mesna":["mesnex","uromitexan"],
  "leucovorin":["folinic acid","wellcovorin","citrovorum"],
  "palifermin":["kepivance"],
  "amifostine":["ethyol"],
  "rasburicase":["elitek","fasturtec"],
  "allopurinol":["zyloprim","aloprim"],
};
"""
